1, upgrade zigup; 2, update zig snippnet(add `std` template); 3, update system env

diff --git a/tool/zigup b/tool/zigup
--- a/tool/zigup
+++ b/tool/zigup
@@ -1,13 +1,34 @@
 #!/usr/bin/env bash
 
 old_version=$(zig version)
-cd /Users/xiaoxiwang/Work/study-demo/zig || exit 1
+cd ~/zig || exit 1
 
-http https://ziglang.org/download/index.json | jq  '.master."x86_64-macos".tarball' | \
-    xargs -I{} -r curl -fSL -o zig-macos-x86_64.tar.xz {}
-tar -xvzf zig-macos-x86_64.tar.xz
-[ -d zig-macos-x86_64.tar.xz ] && trash zig-macos-x86_64.tar.xz
-[ -d zig ] && trash zig
-mv zig-macos-x86_64-0.*-dev.* zig
+download=$(http https://ziglang.org/download/index.json | jq  '.master."x86_64-macos".tarball' | sed -e "s/\"//g" )
+#file=$(echo "${download##*/}")
+file=$(basename "$download")  
+version=$(echo "$file" | sed -e "s/.*64-//" -e "s/.tar.xz//")
+
+if [[ -z "$file"  ||  -z "$version" ]]; then
+    echo "get download url filed..."
+    exit 1
+fi
+
+# download...
+curl -fSL -o "$file" "$download"
+
+[ ! -f "$file" ] && echo "download $file failed! ...." && exit 1
+
+target_dir=~/zig/"$version"
+if [[ -d $target_dir ]]; then
+  trash "$target_dir"
+fi
+
+tar -xvzf "$file" 
+mv "zig-macos-x86_64-$version" "$version"
+
+[ -f "$file" ] && trash "$file"
+
+[ -d ./master ] && trash ./master
+ln -s ./"$version" ./master
 
 printf "\033[0m %-15s\033[36m%s" "zig version:" "$old_version => $(zig version)"
